### ISSUE TITLE
Can it be used for indoor scene point clouds?

### ISSUE THREAD

**Issue by ayaan-mphasis** [Yarroudh/segment-lidar#10]

**Comment by Yarroudh** [comment]
Hello @ayaan-mphasis,
The short answer is no. This version is adapted for aerial LiDAR. Next version will add other features, espacially view, so the package can be applied to MLS and TLS outdoot/indoor datasets.

**Comment by ayaan-mphasis** [comment]
Okay thanks!, Would I need annotations for point cloud scenes in order to use SAM3D? If you are aware of that

**Comment by Yarroudh** [comment]
> Okay thanks!, Would I need annotations for point cloud scenes in order to use SAM3D? If you are aware of that

No, but the point cloud should have RGB values the same as segment-lidar.

**Comment by ayaan-mphasis** [comment]
Okay, but if I do need the bounding boxes for the segmented objects in SAM3D for other purposes can I get them?

**Comment by Yarroudh** [comment]
I think you should ask this question in SAM3D repository, they will definitely guide you. Otherwise, you can try writing your own code that extract the bbox for each segment (minx, maxx, miny, maxy, minz, maxz)
