### ISSUE TITLE
import isse

### ISSUE THREAD

**Issue by sanjivjha** [Yarroudh/segment-lidar#12]
Hi I install the package as given in the guide. 
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from segment_lidar import samlidar
 
ImportError: cannot import name 'samlidar' from 'segment_lidar' (/Users/sanjij/anaconda3/envs/geospatial_demo/lib/python3.9/site-packages/segment_lidar/__init__.py)

please help

**Comment by Yarroudh** [comment]
Hello, how did you install segment-lidar in your environment?

**Comment by sanjivjha** [comment]
first created the env and then pip install on Mac Pro m1 laptop

**Comment by mashnoon1234** [comment]
Hi @Yarroudh,

I have the same issue as @sanjivjha. I followed the instructions mentioned [here](https://yarroudh.gitbook.io/segment-lidar/installation). However, the statement `python -c "import segment_lidar; print(segment_lidar.__version__)"` did not return a version number.

Systems Specs:
Running MacOS Ventura ARM

**Comment by Yarroudh** [comment]
@sanjivjha @mashnoon1234 
I see that the problem only occurs on MacOS. Did you try to use the package on another OS?

**Comment by aaorsi** [comment]
Hi! Unfortunately having the same issue on a mac M1 running Ventura as well. Any ideas on a workaround?

**Comment by Yarroudh** [comment]
Hello @aaorsi,
I see that there is a problem on MacOS but I do not understand why. I need to run my tests on Mac to figure it out. Otherwise, you can still use the docker image, or try to install it on another machine with Linux/Windows. This is a bug right now.

**Comment by tanujpareek-94** [comment]
Hello @Yarroudh,
I tried to install segment-lidar on my windows OS, I got this error, with both pip and cloning the repository locally and then running setup.py. 

![Capture](https://github.com/Yarroudh/segment-lidar/assets/116588273/d690ae6f-40f6-49bb-b86d-953ffbd6aec0)

**Comment by labibmalik** [comment]
Hey @tanujpareek-94, just install the following:

winget install Microsoft.VisualStudio.2022.BuildTools --force --override "--wait --passive --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows11SDK.22000"

Everything will be okay after that

**Comment by tanujpareek-94** [comment]
Thank you for the response. I was able to do it easily in Linux though. Probably, it's trying to compile some C++Wrappers. Same issues when installing KPConv on windows.
