### ISSUE TITLE
specify that CSF should be installed

### ISSUE THREAD

**Issue by hugoledoux** [Yarroudh/segment-lidar#13]
to run the example one needs CSF, but you don't specify it as a requirement:

this seems to be the good one? `pip install cloth-simulation-filter`?

**Comment by Yarroudh** [comment]
Hello @hugoledoux,

Thanks for your interest in `segment-lidar`.

Did you install the package from source? CSF is directly installed on your environment when installing `segment-lidar`, either from PyPI or from source. In the [setup.py](https://github.com/Yarroudh/segment-lidar/blob/main/setup.py), the packages is installed from [source](https://github.com/jianboqi/CSF.git) (line 15).

**Comment by hugoledoux** [comment]
No I used pip

**Comment by Yarroudh** [comment]
I think there is a bug in the last version 0.1.8 that was published on PyPI. Thanks for mentioning this issue.
You can always install the package from source to avoid this problem by running:

```bash
git clone https://github.com/Yarroudh/segment-lidar
cd segment-lidar
python setup.py install
```

Or, you can install CSF on you environment:

```bash
pip install git+https://github.com/jianboqi/CSF.git
```

This should resolve the error.

**Comment by Yarroudh** [comment]
Unfortunately, PyPI does not support external dependencies anymore, and CSF pakcage should now be installed manually before installing `segment-lidar` from PyPI. If you opt for installiong from source, I just added the package to `requirements.txt`.

**Comment by hugoledoux** [comment]
why not use that one? https://pypi.org/project/cloth-simulation-filter/

**Comment by Yarroudh** [comment]
Oups, I litterally missed that package on PyPI as I was looking for `CSF`. I thought the package could only be installed from source back then. This solves the issue then. Thanks for the assistance on that.

**Comment by Yarroudh** [comment]
Closing this issue for now, which I consider solved. The package is up to date in PyPI (v0.1.8.5).
Feel free to re-open it if the error re-appear in upcoming versions.
