### ISSUE TITLE
the LAS file should contain RGB, or not?

### ISSUE THREAD

**Issue by hugoledoux** [Yarroudh/segment-lidar#14]
It seems so since you rasterise and SAM is I believe using this, but this not clear.

You mention in the tutorial that AHN4 is used, but there is no RGB provided with AHN4?! Unless you download from geotiles.nl where RGB has been added (but derived product, not the original one).

So: can it work without RGB values? I tried and I get not very good results...

**Comment by Yarroudh** [comment]
Hello @hugoledoux,

SAM is an image-segmentation model. So, the whole idea is to process the point cloud as an image and reproject results on the original points. RGB values are required in this case. If your data have no RGB values, you can calculate some geometric features and use them to colorize the point cloud. For example, `verticality` can help distinguish between some objects in the generated image. Also, CSF filtering can be useful to extract isolated objects in the point cloud. In this case, the package works just like Label Connected Components algorithm.

For AHN-4 data, you are correct. I need to modify the link in the README file to [geotiles.nl](https://geotiles.nl/). Thank you for mentioning this.
