### ISSUE TITLE
Error on installation and dependecies

### ISSUE THREAD

**Issue by philosadelphos** [Yarroudh/segment-lidar#21]
Hi Anass Yarroudh,
Congrats for pulling out this work! Amazing.
I was following this installation tutorial [here](https://yarroudh.github.io/segment-lidar/installation.htmll), and when I run the following command on linux terminal (debian):
 python -c "import segment_lidar; print(segment_lidar.__version__)" 
I always get:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'segment_lidar' has no attribute '__version__'

I've installed python 3.9.0, 3.9.18 or .19 (not sure), now I've 3.11.5 and error remains the same.
Besides  I always have a version conflict for supervision==0.8.0. Because by pip installing or even by git cloning the version end up supervision 0.6.0.

Is there a way to solve for this ? What do you think?
Thank you again

**Comment by philosadelphos** [comment]
I've already solved the issue. What I did was:
1st: 
conda create --name samlidar python=3.9
2nd: 
pip install opencv-python==4.7.0.72 supervision==0.8.0 laszip==0.2.3 open3d==0.17.0 cloth-simulation-filter==1.1.4
3 rd:
conda install --channel conda-forge pycocotools==2.0.6 click==8.1.3 numpy==1.24.3 segment-geospatial==0.8.1 rasterio==1.3.7 laspy==2.4.1 pytorch
4 th (optional):
conda install --channel conda-forge jupyterlab
5 th, go to the folder where the git hub downloaded files are stored and:
touch segment_lidar/__init__.py

Now we are good to with the tutorial commands

**Comment by Yarroudh** [comment]
Hello @philosadelphos,
Thanks for reporting this, I will be looking at that very soon.
Great to know you have fixed the issue locally.

**Comment by msh003** [comment]
> touch segment_lidar/**init**.py

Thank you for your sharing the solution. wht is init.py in
touch segment_lidar/init.py ?
