### ISSUE TITLE
Just top view?

### ISSUE THREAD

**Issue by aditdoshi333** [Yarroudh/segment-lidar#3]
Is it inferencing just the top view?

<img width="824" alt="Screenshot 2023-06-09 at 7 06 41 PM" src="https://github.com/Yarroudh/segment-lidar/assets/23434856/afd16829-9c22-476c-a403-13118f2e8e1d">

The results are pretty bad!

**Comment by satyajitghana** [comment]
I’ve tried it too, the results are so much worse. The results shown in the readme are very very specific. It only works if you take one LiDAR frame from front view.

the results I got are the worst. Even segment anything 3d is much much better than this.

**Comment by Yarroudh** [comment]
Are you running the algorithm on mobile mapping LiDAR data? This version is adapted to aerial LiDAR data that are mainly geospatial data and not indoor LiDAR.

**Comment by Yarroudh** [comment]
Hello @aditdoshi333,
Can you provide more information about your data and send me a sample?
The second version of segment-lidar is under test, and I think the new features would be useful for this case.

**Comment by Cipher-zzz** [comment]
Hello @Yarroudh,

Thanks for your great work!

I am looking forward to seeing your second version.

Here is a good mobile laser scanner data: https://npm3d.fr/paris-lille-3d

**Comment by Yarroudh** [comment]
Hello, 
We just added the possibility to define your own view as a PINHOLE camera.
This is included in the latest version 0.2.0.
