### ISSUE TITLE
Working with the new VPC format?

### ISSUE THREAD

**Issue by cooph2022** [Yarroudh/segment-lidar#4]
Request : Ability to import & segment the new VPC format!

https://www.lutraconsulting.co.uk/blog/2023/06/08/virtual-point-clouds/

**Comment by Yarroudh** [comment]
Hello @cooph2022,

The second version of **segment-lidar** should support all common lidar file formats (npy, ply, pcd, obj, ept, etc.).
Are there any packages in Python that supports reading VPC format? Can we read the file in PDAL using **readers.stac**?

Thanks

**Comment by cooph2022** [comment]
Perhaps I was overzealous, given the timeframe! I think we're waiting yet...

https://github.com/PDAL/PDAL/issues/4072

**Comment by cooph2022** [comment]
I believe we're in business!

https://github.com/PDAL/PDAL/releases/tag/2.5.5
