### ISSUE TITLE
local variable 'lidar' referenced before assignment

### ISSUE THREAD

**Issue by AbdelghaniTamort** [Yarroudh/segment-lidar#5]
The following error occurs while writing the segmented point cloud : 

[error.log](https://github.com/Yarroudh/segment-lidar/files/11866416/error.log)

**Comment by Yarroudh** [comment]
Hello @AbdelghaniTamort,
Thanks for your feedback. This error should be corrected in the next version 0.1.6. I'll release it in a week.
