### ISSUE TITLE
Saving separate segmented point cloud files

### ISSUE THREAD

**Issue by minar09** [Yarroudh/segment-lidar#7]
Hi, thanks for the great work. Is there a way to save each segmented object/instance as a separate point cloud file? Thank you.

**Comment by Yarroudh** [comment]
For now, there is no such option. When writing the results, the file in output contains a new scalar field `segment_id`. You can read this file with `laspy` and try to separate points based on that scalar field. However, the easiest way to do so is to read you file in `CloudCompare`, choose `segment_id` as scalar field, then segment the cloud based on that attribute and save the results. We can think about adding such a feature in the next version.

**Comment by minar09** [comment]
Thank you very much @Yarroudh for your detailed response. Really appreciate it. Thanks.
